-- DATA ARCHITECT: Apply the complete schema upgrade atomically so failed deployments leave no partial state.
begin;

-- DATA ARCHITECT: Preserve the existing backend contract while exposing explicit current-style and freshness columns.
create table if not exists public.style_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  profile jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  current_style jsonb not null default '{}'::jsonb,
  last_updated timestamptz not null default now()
);

alter table public.style_profiles
  add column if not exists profile jsonb,
  add column if not exists updated_at timestamptz,
  add column if not exists current_style jsonb,
  add column if not exists last_updated timestamptz;

update public.style_profiles
set
  profile = coalesce(profile, current_style, '{}'::jsonb),
  current_style = coalesce(current_style, profile, '{}'::jsonb),
  updated_at = coalesce(updated_at, last_updated, now()),
  last_updated = coalesce(last_updated, updated_at, now())
where
  profile is null
  or current_style is null
  or updated_at is null
  or last_updated is null;

alter table public.style_profiles
  alter column profile set default '{}'::jsonb,
  alter column profile set not null,
  alter column updated_at set default now(),
  alter column updated_at set not null,
  alter column current_style set default '{}'::jsonb,
  alter column current_style set not null,
  alter column last_updated set default now(),
  alter column last_updated set not null;

-- DATA ARCHITECT: Synchronize old and new style-profile column names for backward-compatible reads and writes.
create or replace function public.sync_style_profile_columns()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    if new.current_style is distinct from '{}'::jsonb
       and new.profile is not distinct from '{}'::jsonb then
      new.profile = new.current_style;
    else
      new.current_style = new.profile;
    end if;
  elsif new.current_style is distinct from old.current_style
        and new.profile is not distinct from old.profile then
    new.profile = new.current_style;
  else
    new.current_style = new.profile;
  end if;

  new.updated_at = now();
  new.last_updated = new.updated_at;
  return new;
end;
$$;

drop trigger if exists style_profiles_set_updated_at on public.style_profiles;
drop trigger if exists style_profiles_sync_columns on public.style_profiles;
create trigger style_profiles_sync_columns
before insert or update on public.style_profiles
for each row execute function public.sync_style_profile_columns();

-- DATA ARCHITECT: Preserve legacy text ownership untouched and add the auth-user foreign key to UUID deployments.
do $$
declare
  user_id_type text;
begin
  select data_type
  into user_id_type
  from information_schema.columns
  where table_schema = 'public'
    and table_name = 'style_profiles'
    and column_name = 'user_id';

  if user_id_type <> 'uuid' then
    raise notice 'style_profiles.user_id remains legacy text; run auth_hardening_migration.sql after reviewing unmatched rows';
  end if;

  if user_id_type = 'uuid'
     and not exists (
       select 1
       from pg_constraint c
       join pg_class t on t.oid = c.conrelid
       join pg_namespace n on n.oid = t.relnamespace
       where n.nspname = 'public'
         and t.relname = 'style_profiles'
         and c.contype = 'f'
         and c.confrelid = 'auth.users'::regclass
     ) then
    alter table public.style_profiles
      add constraint style_profiles_user_id_fkey
      foreign key (user_id) references auth.users(id) on delete cascade;
  end if;
end;
$$;

-- DATA ARCHITECT: Store every submitted original, generated rewrite, user outcome, learning feedback, and lifecycle timestamp.
create table if not exists public.email_history (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  original_text text not null,
  generated_rewrite text not null,
  final_version text,
  feedback jsonb not null default '{}'::jsonb,
  influenced_traits text[] not null default '{}'::text[],
  submitted_at timestamptz not null default now(),
  finalized_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.email_history
  add column if not exists user_id uuid,
  add column if not exists original_text text,
  add column if not exists generated_rewrite text,
  add column if not exists final_version text,
  add column if not exists feedback jsonb,
  add column if not exists influenced_traits text[],
  add column if not exists submitted_at timestamptz,
  add column if not exists finalized_at timestamptz,
  add column if not exists created_at timestamptz,
  add column if not exists updated_at timestamptz;

alter table public.email_history
  alter column feedback set default '{}'::jsonb,
  alter column influenced_traits set default '{}'::text[],
  alter column submitted_at set default now(),
  alter column created_at set default now(),
  alter column updated_at set default now();

update public.email_history
set
  feedback = coalesce(feedback, '{}'::jsonb),
  influenced_traits = coalesce(influenced_traits, '{}'::text[]),
  submitted_at = coalesce(submitted_at, created_at, now()),
  created_at = coalesce(created_at, submitted_at, now()),
  updated_at = coalesce(updated_at, created_at, submitted_at, now())
where
  feedback is null
  or influenced_traits is null
  or submitted_at is null
  or created_at is null
  or updated_at is null;

alter table public.email_history
  alter column user_id set not null,
  alter column original_text set not null,
  alter column generated_rewrite set not null,
  alter column feedback set not null,
  alter column influenced_traits set not null,
  alter column submitted_at set not null,
  alter column created_at set not null,
  alter column updated_at set not null;

-- DATA ARCHITECT: Store periodic immutable style snapshots and a bounded completeness score per user.
create table if not exists public.persona_snapshots (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  style jsonb not null default '{}'::jsonb,
  completeness numeric(5,4) not null default 0,
  captured_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  constraint persona_snapshots_completeness_check
    check (completeness >= 0 and completeness <= 1)
);

alter table public.persona_snapshots
  add column if not exists user_id uuid,
  add column if not exists style jsonb,
  add column if not exists completeness numeric(5,4),
  add column if not exists captured_at timestamptz,
  add column if not exists created_at timestamptz;

alter table public.persona_snapshots
  alter column style set default '{}'::jsonb,
  alter column completeness set default 0,
  alter column captured_at set default now(),
  alter column created_at set default now();

update public.persona_snapshots
set
  style = coalesce(style, '{}'::jsonb),
  completeness = coalesce(completeness, 0),
  captured_at = coalesce(captured_at, created_at, now()),
  created_at = coalesce(created_at, captured_at, now())
where
  style is null
  or completeness is null
  or captured_at is null
  or created_at is null;

alter table public.persona_snapshots
  alter column user_id set not null,
  alter column style set not null,
  alter column completeness set not null,
  alter column captured_at set not null,
  alter column created_at set not null;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conrelid = 'public.persona_snapshots'::regclass
      and conname = 'persona_snapshots_completeness_check'
  ) then
    alter table public.persona_snapshots
      add constraint persona_snapshots_completeness_check
      check (completeness >= 0 and completeness <= 1) not valid;
  end if;
end;
$$;

-- DATA ARCHITECT: Store queryable style labels as a native text array with per-user freshness metadata.
create table if not exists public.style_tags (
  user_id uuid primary key references auth.users(id) on delete cascade,
  tags text[] not null default '{}'::text[],
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.style_tags
  add column if not exists user_id uuid,
  add column if not exists tags text[],
  add column if not exists created_at timestamptz,
  add column if not exists updated_at timestamptz;

alter table public.style_tags
  alter column tags set default '{}'::text[],
  alter column created_at set default now(),
  alter column updated_at set default now();

update public.style_tags
set
  tags = coalesce(tags, '{}'::text[]),
  created_at = coalesce(created_at, updated_at, now()),
  updated_at = coalesce(updated_at, created_at, now())
where tags is null or created_at is null or updated_at is null;

alter table public.style_tags
  alter column user_id set not null,
  alter column tags set not null,
  alter column created_at set not null,
  alter column updated_at set not null;

-- DATA ARCHITECT: Restore missing auth-user foreign keys on pre-existing versions of the new tables.
do $$
declare
  table_name text;
  constraint_name text;
begin
  foreach table_name in array array['email_history', 'persona_snapshots', 'style_tags']
  loop
    constraint_name := table_name || '_user_id_fkey';
    if not exists (
      select 1
      from pg_constraint c
      where c.conrelid = format('public.%I', table_name)::regclass
        and c.contype = 'f'
        and c.confrelid = 'auth.users'::regclass
    ) then
      execute format(
        'alter table public.%I add constraint %I foreign key (user_id) references auth.users(id) on delete cascade',
        table_name,
        constraint_name
      );
    end if;
  end loop;
end;
$$;

-- DATA ARCHITECT: Maintain modification and finalization timestamps without relying on application callers.
create or replace function public.set_data_architect_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  new.updated_at = now();
  if tg_table_name = 'email_history'
     and new.final_version is not null
     and new.finalized_at is null then
    new.finalized_at = now();
  end if;
  return new;
end;
$$;

drop trigger if exists email_history_set_updated_at on public.email_history;
create trigger email_history_set_updated_at
before insert or update on public.email_history
for each row execute function public.set_data_architect_updated_at();

drop trigger if exists style_tags_set_updated_at on public.style_tags;
create trigger style_tags_set_updated_at
before insert or update on public.style_tags
for each row execute function public.set_data_architect_updated_at();

-- DATA ARCHITECT: Add indexes for per-user timelines, completeness queries, and array containment searches.
create index if not exists email_history_user_submitted_idx
  on public.email_history (user_id, submitted_at desc);
create index if not exists persona_snapshots_user_captured_idx
  on public.persona_snapshots (user_id, captured_at desc);
create index if not exists persona_snapshots_user_completeness_idx
  on public.persona_snapshots (user_id, completeness desc);
create index if not exists style_tags_tags_gin_idx
  on public.style_tags using gin (tags);

-- DATA ARCHITECT: Enable RLS and remove every prior policy so no permissive legacy rule can retain cross-user access.
alter table public.style_profiles enable row level security;
alter table public.email_history enable row level security;
alter table public.persona_snapshots enable row level security;
alter table public.style_tags enable row level security;

do $$
declare
  policy_record record;
begin
  for policy_record in
    select schemaname, tablename, policyname
    from pg_policies
    where schemaname = 'public'
      and tablename in (
        'style_profiles',
        'email_history',
        'persona_snapshots',
        'style_tags'
      )
  loop
    execute format(
      'drop policy if exists %I on %I.%I',
      policy_record.policyname,
      policy_record.schemaname,
      policy_record.tablename
    );
  end loop;
end;
$$;

-- DATA ARCHITECT: Restrict style profiles to explicit owner-only CRUD for authenticated users.
create policy style_profiles_select_own
on public.style_profiles for select to authenticated
using (auth.uid()::text = user_id::text);
create policy style_profiles_insert_own
on public.style_profiles for insert to authenticated
with check (auth.uid()::text = user_id::text);
create policy style_profiles_update_own
on public.style_profiles for update to authenticated
using (auth.uid()::text = user_id::text)
with check (auth.uid()::text = user_id::text);
create policy style_profiles_delete_own
on public.style_profiles for delete to authenticated
using (auth.uid()::text = user_id::text);

-- DATA ARCHITECT: Restrict email history to explicit owner-only CRUD for authenticated users.
create policy email_history_select_own
on public.email_history for select to authenticated
using (auth.uid() = user_id);
create policy email_history_insert_own
on public.email_history for insert to authenticated
with check (auth.uid() = user_id);
create policy email_history_update_own
on public.email_history for update to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);
create policy email_history_delete_own
on public.email_history for delete to authenticated
using (auth.uid() = user_id);

-- DATA ARCHITECT: Restrict persona snapshots to explicit owner-only CRUD for authenticated users.
create policy persona_snapshots_select_own
on public.persona_snapshots for select to authenticated
using (auth.uid() = user_id);
create policy persona_snapshots_insert_own
on public.persona_snapshots for insert to authenticated
with check (auth.uid() = user_id);
create policy persona_snapshots_update_own
on public.persona_snapshots for update to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);
create policy persona_snapshots_delete_own
on public.persona_snapshots for delete to authenticated
using (auth.uid() = user_id);

-- DATA ARCHITECT: Restrict style tags to explicit owner-only CRUD for authenticated users.
create policy style_tags_select_own
on public.style_tags for select to authenticated
using (auth.uid() = user_id);
create policy style_tags_insert_own
on public.style_tags for insert to authenticated
with check (auth.uid() = user_id);
create policy style_tags_update_own
on public.style_tags for update to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);
create policy style_tags_delete_own
on public.style_tags for delete to authenticated
using (auth.uid() = user_id);

-- DATA ARCHITECT: Commit only after tables, compatibility behavior, indexes, triggers, and isolation policies all succeed.
commit;
