-- DATA ARCHITECT: Upgrade Style Profile storage for the full rebuild contract.
begin;

-- DATA ARCHITECT: Add first-class profile summary fields while preserving the existing JSON profile contract.
alter table public.style_profiles
  add column if not exists persona_label text not null default 'Emerging Voice',
  add column if not exists persona_summary text not null default 'PhraseAI is still learning this writing style.',
  add column if not exists profile_completeness numeric(5,4) not null default 0,
  add column if not exists emails_analyzed integer not null default 0;

-- DATA ARCHITECT: Bound dashboard-facing aggregate fields.
do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.style_profiles'::regclass
      and conname = 'style_profiles_profile_completeness_check'
  ) then
    alter table public.style_profiles
      add constraint style_profiles_profile_completeness_check
      check (profile_completeness >= 0 and profile_completeness <= 1) not valid;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.style_profiles'::regclass
      and conname = 'style_profiles_emails_analyzed_check'
  ) then
    alter table public.style_profiles
      add constraint style_profiles_emails_analyzed_check
      check (emails_analyzed >= 0) not valid;
  end if;
end;
$$;

-- DATA ARCHITECT: Keep JSON and first-class columns synchronized for old and new clients.
create or replace function public.sync_style_profile_columns()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_profile jsonb;
begin
  if tg_op = 'INSERT' then
    if new.current_style is distinct from '{}'::jsonb
       and new.profile is not distinct from '{}'::jsonb then
      new.profile = new.current_style;
    else
      new.current_style = new.profile;
    end if;
  elsif new.current_style is distinct from old.current_style
        and new.profile is not distinct from old.profile then
    new.profile = new.current_style;
  else
    new.current_style = new.profile;
  end if;

  v_profile := coalesce(new.profile, '{}'::jsonb);
  new.persona_label = coalesce(nullif(new.persona_label, ''), nullif(v_profile ->> 'persona_label', ''), 'Emerging Voice');
  new.persona_summary = coalesce(nullif(new.persona_summary, ''), nullif(v_profile ->> 'persona_summary', ''), 'PhraseAI is still learning this writing style.');
  new.profile_completeness = greatest(0, least(1, coalesce(new.profile_completeness, (v_profile ->> 'profile_completeness')::numeric, 0)));
  new.emails_analyzed = greatest(0, coalesce(new.emails_analyzed, (v_profile ->> 'emails_analyzed')::integer, ((v_profile -> 'stats') ->> 'learned_examples')::integer, 0));
  new.updated_at = now();
  new.last_updated = new.updated_at;
  return new;
end;
$$;

-- DATA ARCHITECT: One immutable public feedback event per user action, including manual edited rewrites.
create table if not exists public.style_feedback (
  id bigint generated by default as identity primary key,
  rewrite_id bigint not null references public.email_history(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  feedback_type text not null check (feedback_type in ('good', 'off', 'edited')),
  trait_affected text,
  user_note text,
  manual_edit text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- DATA ARCHITECT: Make the feedback migration idempotent for existing partially-created tables.
alter table public.style_feedback
  add column if not exists rewrite_id bigint,
  add column if not exists user_id uuid,
  add column if not exists feedback_type text,
  add column if not exists trait_affected text,
  add column if not exists user_note text,
  add column if not exists manual_edit text,
  add column if not exists metadata jsonb,
  add column if not exists created_at timestamptz,
  add column if not exists updated_at timestamptz;

-- DATA ARCHITECT: Normalize style_feedback defaults before tightening constraints.
update public.style_feedback
set
  metadata = coalesce(metadata, '{}'::jsonb),
  created_at = coalesce(created_at, now()),
  updated_at = coalesce(updated_at, created_at, now())
where metadata is null or created_at is null or updated_at is null;

alter table public.style_feedback
  alter column rewrite_id set not null,
  alter column user_id set not null,
  alter column feedback_type set not null,
  alter column metadata set default '{}'::jsonb,
  alter column metadata set not null,
  alter column created_at set default now(),
  alter column created_at set not null,
  alter column updated_at set default now(),
  alter column updated_at set not null;

-- DATA ARCHITECT: Support evolution comparisons and tie each snapshot to the email that created it.
alter table public.persona_snapshots
  add column if not exists source_history_id bigint references public.email_history(id) on delete set null,
  add column if not exists persona_label text not null default 'Emerging Voice',
  add column if not exists persona_summary text not null default '';

-- DATA ARCHITECT: Keep feedback timestamps fresh without mutating immutable event content.
create or replace function public.set_style_feedback_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists style_feedback_set_updated_at on public.style_feedback;
create trigger style_feedback_set_updated_at
before insert or update on public.style_feedback
for each row execute function public.set_style_feedback_updated_at();

-- DATA ARCHITECT: Query paths for history feed, impact summary, and edited-feedback analysis.
create index if not exists style_feedback_user_created_idx
  on public.style_feedback (user_id, created_at desc);
create index if not exists style_feedback_rewrite_created_idx
  on public.style_feedback (rewrite_id, created_at desc);
create index if not exists persona_snapshots_source_history_idx
  on public.persona_snapshots (source_history_id);

-- DATA ARCHITECT: Enable and replace feedback RLS with strict owner plus rewrite ownership checks.
alter table public.style_feedback enable row level security;

do $$
declare
  policy_record record;
begin
  for policy_record in
    select schemaname, tablename, policyname
    from pg_policies
    where schemaname = 'public'
      and tablename = 'style_feedback'
  loop
    execute format(
      'drop policy if exists %I on %I.%I',
      policy_record.policyname,
      policy_record.schemaname,
      policy_record.tablename
    );
  end loop;
end;
$$;

-- DATA ARCHITECT: Users can read only feedback events attached to their own rewrite history.
create policy style_feedback_select_own
on public.style_feedback for select to authenticated
using (
  auth.uid() = user_id
  and exists (
    select 1 from public.email_history h
    where h.id = rewrite_id and h.user_id = auth.uid()
  )
);

-- DATA ARCHITECT: Users can write only feedback events attached to their own rewrite history.
create policy style_feedback_insert_own
on public.style_feedback for insert to authenticated
with check (
  auth.uid() = user_id
  and exists (
    select 1 from public.email_history h
    where h.id = rewrite_id and h.user_id = auth.uid()
  )
);

-- DATA ARCHITECT: Users can amend their own feedback notes/manual edits only.
create policy style_feedback_update_own
on public.style_feedback for update to authenticated
using (
  auth.uid() = user_id
  and exists (
    select 1 from public.email_history h
    where h.id = rewrite_id and h.user_id = auth.uid()
  )
)
with check (
  auth.uid() = user_id
  and exists (
    select 1 from public.email_history h
    where h.id = rewrite_id and h.user_id = auth.uid()
  )
);

-- DATA ARCHITECT: Users can delete only their own feedback events.
create policy style_feedback_delete_own
on public.style_feedback for delete to authenticated
using (
  auth.uid() = user_id
  and exists (
    select 1 from public.email_history h
    where h.id = rewrite_id and h.user_id = auth.uid()
  )
);

-- DATA ARCHITECT: Schema upgrade commits only after table, trigger, indexes, and RLS exist.
commit;
